### PR TITLE
Serialize lfs

### LINKED ISSUE #222: Connecting/Reconnecting a nrf52 peripheral to a central can corrupt the LittleFS FS where pairing information is stored.
- Please provide details that help us to reproduce your issue
That's a hard one... generally disconnecting and reconnecting can cause this issue but doesn't happen all the time.  It's not a critical problem when a central (nrf52832) reconnects to a peripheral (nrf52832) but is an issue when a computer reconnects to a "faulty" peripheral.  It appears that a nrf52 central will re-negociate the pairing information.  However, a computer will retain the pairing information and keep retrying (as seen by the toggling back and forth between paired and connected on windows 10).

I suspect the issue occurs on the original pairing and not the reconnection.

  - Your Board and BSP version
       BSP Library : 0.9.3
       Bootloader  : s132 6.1.1 r1
  - Your OS: 
       Windows 10
  - Steps to reproduce, or better your (simplified) sketch if possible
Can't yet identify the steps to reproduce or the root cause. (will keep working on that)

  - Serial debug log: all at Debug Level 2:
Problem 1 (on reconnection - but not the actual root cause):

```
lfs error:494: Corrupted dir pair at 3 2
virtual bool LittleFS::rmdir_r(const char*): 373: verify failed, error = LFS_ERR_CORRUPT

```

Problem 2 (after restarting):

```
Peripheral Paired Devices: 
lfs error:494: Corrupted dir pair at 124 123
BluefruitFS::File LittleFS::_open_dir(const char*): 281: verify failed, error = LFS_ERR_CORRUPT

```

When windows tries to reconnect, all we see is this (and it keeps repeating):

```
[BLE   ] BLE_GAP_EVT_CONNECTED : Conn Handle = 0
[GAP   ] Conn Interval= 11.250000
[BLE   ] BLE_GAP_EVT_SEC_INFO_REQUEST : Conn Handle = 0
lfs error:494: Corrupted dir pair at 124 123
virtual BluefruitFS::File LittleFS::open(const char*, uint8_t): 313: verify failed, error = LFS_ERR_CORRUPT
[BLE   ] BLE_GAP_EVT_DISCONNECTED : Conn Handle = 0
[GAP   ] Disconnect Reason 0x13
```

Even after loading the "Clear Bonds" program. I was left with the same problem:

```
Bluefruit52 Clear Bonds Example
-------------------------------

[CFG   ] SoftDevice's RAM requires: 0x20002530
lfs error:494: Corrupted dir pair at 3 2
lfs error:494: Corrupted dir pair at 3 2
virtual bool LittleFS::mkdir(const char*): 339: verify failed, error = LFS_ERR_CORRUPT
lfs error:494: Corrupted dir pair at 3 2
lfs error:494: Corrupted dir pair at 3 2
virtual bool LittleFS::mkdir(const char*): 339: verify failed, error = LFS_ERR_CORRUPT

----- Before -----

lfs error:494: Corrupted dir pair at 3 2
virtual BluefruitFS::File LittleFS::open(const char*, uint8_t): 313: verify failed, error = LFS_ERR_CORRUPT

lfs error:494: Corrupted dir pair at 3 2
virtual BluefruitFS::File LittleFS::open(const char*, uint8_t): 313: verify failed, error = LFS_ERR_CORRUPT

lfs error:494: Corrupted dir pair at 3 2
virtual bool LittleFS::rmdir_r(const char*): 373: verify failed, error = LFS_ERR_CORRUPT
lfs error:494: Corrupted dir pair at 3 2
virtual bool LittleFS::mkdir(const char*): 339: verify failed, error = LFS_ERR_CORRUPT
lfs error:494: Corrupted dir pair at 3 2
virtual bool LittleFS::rmdir_r(const char*): 373: verify failed, error = LFS_ERR_CORRUPT
lfs error:494: Corrupted dir pair at 3 2
virtual bool LittleFS::mkdir(const char*): 339: verify failed, error = LFS_ERR_CORRUPT

----- After  -----

lfs error:494: Corrupted dir pair at 3 2
virtual BluefruitFS::File LittleFS::open(const char*, uint8_t): 313: verify failed, error = LFS_ERR_CORRUPT

lfs error:494: Corrupted dir pair at 3 2
virtual BluefruitFS::File LittleFS::open(const char*, uint8_t): 313: verify failed, error = LFS_ERR_CORRUPT
```

At that point, the only way I was able to recover FS functionality was to re-flash the bootloader and re-flash clearbonds which gave me: 

```
[CFG   ] SoftDevice's RAM requires: 0x20002530
lfs error:494: Corrupted dir pair at 0 1
lfs error:2222: Invalid superblock at 0 1
[IFLASH] Format internal file system
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS

----- Before -----



[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS

----- After  -----

```

After reflashing over the reformatted file system, it works fine, until the offending situation occurs and the problem happens again.

When the bonding information is wiped by reflashing the bootloader, I can unpair and reconnect in windows 10 and I get these messages when pairing:

```

[GAP   ] Conn Interval= 11.250000
[BLE   ] BLE_GATTC_EVT_CHAR_VAL_BY_UUID_READ_RSP : Conn Handle = 1
[BLE   ] BLE_GAP_EVT_SEC_PARAMS_REQUEST : Conn Handle = 1
[PRPH  ] Connected to 1 TOASTER
[BLE   ] BLE_GATTS_EVT_EXCHANGE_MTU_REQUEST : Conn Handle = 1
[GAP   ] ATT MTU is changed to 23
[BLE   ] BLE_GAP_EVT_CONN_SEC_UPDATE : Conn Handle = 1
[BOND  ] CCCD setting not found
[BLE   ] BLE_GAP_EVT_AUTH_STATUS : Conn Handle = 1
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[BLE   ] BLE_GATTC_EVT_CHAR_VAL_BY_UUID_READ_RSP : Conn Handle = 1
[BOND  ] Saved keys for "TOASTER" to file /adafruit/bond_prph/59d1 ( 90 bytes )
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[BLE   ] BLE_GATTS_EVT_WRITE : Conn Handle = 1
[BLE   ] BLE_GAP_EVT_CONN_PARAM_UPDATE : Conn Handle = 1
[GAP   ] Conn Interval= 11.250000
[BLE   ] BLE_GATTS_EVT_WRITE : Conn Handle = 1
[GATTS ] attr's cccd
000:  01 00                                           | ..

[BOND  ] Saved CCCD setting to file /adafruit/bond_prph/59d1 ( offset = 90, len = 44 bytes )
[BLE   ] BLE_GATTS_EVT_WRITE : Conn Handle = 1
[GATTS ] attr's cccd
000:  01 00                                           | ..

[BLE   ] BLE_GAP_EVT_CONN_PARAM_UPDATE : Conn Handle = 1
[GAP   ] Conn Interval= 56.250000
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[BLE   ] BLE_GATTS_EVT_WRITE : Conn Handle = 1
[GATTS ] attr's cccd
000:  01 00                                           | ..

[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[BOND  ] Saved CCCD setting to file /adafruit/bond_prph/59d1 ( offset = 90, len = 44 bytes )
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[BLE   ] BLE_GAP_EVT_CONN_PARAM_UPDATE : Conn Handle = 1
[GAP   ] Conn Interval= 11.250000
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[BOND  ] Saved CCCD setting to file /adafruit/bond_prph/59d1 ( offset = 90, len = 44 bytes )
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
[BLE   ] BLE_GATTS_EVT_WRITE : Conn Handle = 1
[GATTS ] attr's value, uuid = 0x2A4D
000:  01                                              | .

[HID   ] Keyboard LED : 0x01
[SOC   ] NRF_EVT_FLASH_OPERATION_SUCCESS
```

### LINKED ISSUE #227: InternalFS Corrupt Blocks
Board: nRF52840 Express
MacOS
Bootloader 0.2.6
Arduino IDE 1.8.8

I'm trying to write a string to the InternalFS, and I get the following error sporadically.
```
12:59:53.579 -> lfs error:494: Corrupted dir pair at 0 1
12:59:53.579 -> lfs error:2222: Invalid superblock at 0 1
12:59:53.579 -> [IFLASH] Format internal file system
```
The only way to fix it is to InternalFS.format(true).  I can't quite pinpoint what is causing it, so I don't think posting code will help.  Having said that, I did some research and discovered the following which may/may not help:

1) InternalFS File.write(buffer, size) does not overwrite the file. It appends to it.  I incremented a counter every 1s and read/write it to the same file and got the following output:
```
1
12
123
```
Instead, I would expect the following:
```
1
2
3
```
Which takes me to 2). 

2)  In order to overwrite the file contents, I remove the file and create a new one. Removing a file takes a VERY long time (a few seconds).  I found the following article from Nordic that describes how internal flash is slow to remove:

https://devzone.nordicsemi.com/f/nordic-q-a/20197/nrf52-flash-memory-vs-eeprom

It could be that since I'm running BLE and removing files, RTOS is switching tasks which is causing issues?  Anyways, right now I've created an RTOS queue to serialize my writes, and/or maybe I need to add a mutex.  I think once ExternalFS is up and running these kind of problems go away.. but I thought I'd post my findings here.

### LINKED ISSUE #325: nRF52832 frequently connect/disconnect occur assertion "head >= 2 && head <= lfs->cfg->block_count"
**Hi~
I'm using a nRF52832 feather to build keyboard. I found a strange bug when iPhone disconnecting and reconnecting keyboard frequently can cause error:**

10:36:26.458 -> assertion "head >= 2 && head <= lfs->cfg->block_count" failed: file "C:\Users\cc\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.11.1\libraries\Adafruit_LittleFS\src\littlefs\lfs.c", line 1144, function: lfs_ctz_find
10:36:33.668 -> assertion "head >= 2 && head <= lfs->cfg->block_count" failed: file "C:\Users\cc\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.11.1\libraries\Adafruit_LittleFS\src\littlefs\lfs.c", line 1144, function: lfs_ctz_find

**In my project, iPhone is peripheral and keyboard is cent, iPhone connect keyboard when it started. The connect/disconnect callback code like this:**

```
void prphConnectCallback(uint16_t conn_handle) {
  // Get the reference to current connection
  BLEConnection* connection = Bluefruit.Connection(conn_handle);
  perph_conn_handle = conn_handle;

  // debug information
  char peer_name[32] = { 0 };
  connection->getPeerName(peer_name, sizeof(peer_name));

  LOG("[Prph] Connected handle: %d, name: %s\r\n", conn_handle, peer_name);
}

void prphDisconnectCallback(uint16_t conn_handle, uint8_t reason) {
  (void) conn_handle;
  (void) reason;

  Bluefruit.Advertising.stop();
  delay(10);

  //startAdv();
  Bluefruit.Advertising.start(0);
  // debug information
  LOG("[Prph] Disconnected\r\n");
}
```

**The complete serial logs is(Level 0):**
02:31:05.162 -> start...
02:31:05.435 -> in low power
02:31:05.468 -> LN-REDOX bluetooth keyboard RHS started
02:31:05.876 -> [SCAN] scanned, start connect...
02:31:06.186 -> [Cent] Connected handle: 0, name: LHS
02:31:10.046 -> [Prph] Connected handle: 1, name: iPhone
02:31:22.517 -> [Prph] Disconnected
02:31:26.375 -> [Prph] Connected handle: 1, name: iPhone (2
02:31:41.828 -> [Prph] Disconnected
02:31:47.139 -> [Prph] Connected handle: 1, name: iPhone (2
02:31:59.740 -> [Prph] Disconnected
02:32:03.654 -> [Prph] Connected handle: 1, name: iPhone (2
02:32:31.155 -> [Prph] Disconnected
02:32:35.173 -> [Prph] Connected handle: 1, name: iPhone (2
02:32:52.566 -> [Prph] Disconnected
02:32:56.388 -> [Prph] Connected handle: 1, name: iPhone (2
02:33:11.480 -> [Prph] Disconnected
02:33:14.658 -> [Prph] Connected handle: 1, name: iPhone (2
02:33:27.269 -> [Prph] Disconnected
02:33:31.146 -> [Prph] Connected handle: 1, name: iPhone (2
02:33:56.366 -> [Prph] Disconnected
02:34:03.249 -> [Prph] Connected handle: 1, name: iPhone (2
02:34:04.756 -> [Prph] Disconnected
02:34:16.321 -> [Prph] Connected handle: 1, name: iPhone (2
02:37:26.456 -> [Prph] Disconnected
02:42:45.820 -> [Prph] Connected handle: 1, name: iPhone (2
02:53:56.825 -> [Prph] Disconnected
08:45:48.984 -> [Prph] Connected handle: 1, name: 
09:03:59.574 -> [Prph] Disconnected
09:33:22.403 -> [Prph] Connected handle: 1, name: iPhone (2
09:34:09.581 -> [Prph] Disconnected
10:03:07.080 -> [Prph] Connected handle: 1, name: iPhone (2
10:03:28.158 -> [Prph] Disconnected
10:23:34.210 -> [Prph] Connected handle: 1, name: 
10:23:34.659 -> [Prph] Disconnected
10:23:42.526 -> [Prph] Connected handle: 1, name: 
10:23:42.526 -> [Prph] Disconnected
10:23:43.323 -> [Prph] Connected handle: 1, name: 
10:23:44.549 -> [Prph] Disconnected
10:23:49.709 -> [Prph] Connected handle: 1, name: 
10:23:51.040 -> [Prph] Disconnected
10:23:53.630 -> [Prph] Connected handle: 1, name: 
10:23:54.343 -> [Prph] Disconnected
10:27:51.664 -> [Prph] Connected handle: 1, name: 
10:27:52.276 -> [Prph] Disconnected
10:27:55.238 -> [Prph] Connected handle: 1, name: 
10:27:55.272 -> [Prph] Disconnected
10:27:56.631 -> [Prph] Connected handle: 1, name: iPhone (2
10:28:13.872 -> [Prph] Disconnected
10:28:26.004 -> [Prph] Connected handle: 1, name: iPhone (2
10:28:27.223 -> [Prph] Disconnected
10:28:32.137 -> [Prph] Connected handle: 1, name: iPhone (2
10:28:33.885 -> [Prph] Disconnected
10:36:19.230 -> [Prph] Connected handle: 1, name: iPhone (2
10:36:26.458 -> assertion "head >= 2 && head <= lfs->cfg->block_count" failed: file "C:\Users\cc\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.11.1\libraries\Adafruit_LittleFS\src\littlefs\lfs.c", line 1144, function: lfs_ctz_find
10:36:33.668 -> assertion "head >= 2 && head <= lfs->cfg->block_count" failed: file "C:\Users\cc\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.11.1\libraries\Adafruit_LittleFS\src\littlefs\lfs.c", line 1144, function: lfs_ctz_find

**I want to know when this error will occur and how to solve it.**

**bootloader: feather_nrf52832_bootloader-0.2.11_s132_6.1.1
bsp: 0.11.1**

@hathach @jeremypoulter 
Plz~

### LINKED ISSUE #350: [Bug] InternalFS analysis: LFS requirements, coherency guarantees
<details>
<summary>original analysis -- useful but may not be cause</summary>

<P>

**Describe the bug**
[ARMmbed/littlefs](https://github.com/ARMmbed/littlefs) allows the `prog` and `erase` functions to return LFS_ERR_CORRUPT.  However, it does not allow the underlying implementation to ignore errors.  Unfortunately, it appears that there are multiple paths where Adafruit's InternalFS can hit an error, but not report that error to LFS.  This bug opened to have clear bug title corresponding to underlying issue.

**Set up (please complete the following information)**
This thread is based on manual code review and analysis of **BSP v0.14.0**.
Corruptions have been reported on both **nRF52832** and **nRF52840**.
See linked issue #325 for an example serial debug log that shows the relevant code paths were hit just prior to a corruption being detected.  Relevant part:

**11:07:35.692** -> [SOC ] **NRF_EVT_FLASH_OPERATION_ERROR**
11:07:36.308 -> [BLE ] BLE_GAP_EVT_DISCONNECTED : Conn Handle = 1
11:07:36.308 -> [GAP ] Disconnect Reason 0x08
11:07:36.308 -> [SOC ] NRF_EVT_FLASH_OPERATION_SUCCESS
11:07:36.475 -> [SOC ] NRF_EVT_FLASH_OPERATION_SUCCESS
**11:07:36.509** -> assertion "head >= 2 && head <= lfs->cfg->block_count" failed: file "C:\Users\cc\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.11.1\libraries\Adafruit_LittleFS\src\littlefs\lfs.c", line 1144, function: lfs_ctz_find

**To Reproduce**
Manually review the code.  Note the multiple code paths where an error is ignored.  Details follow for easy reference (also written at #325).

**Expected behavior**
When an error is reported when programming or erasing the flash, InternalFS must either retry the operation (e.g., up to 5x), or report that the write/erase/flush operation has failed.  This will allow LittleFS to avoid using that page of cache, and maintain data consistency..

**Additional context**
There is a history of hard-to-reproduce file system corruptions (e.g., #325, #227, #226, #222).  Not all have indications of this bug, but then the current BSP has commented-out the trace when errors are reported.

</details>

See [below](https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/350#issuecomment-540158177) for update

### LINKED ISSUE #393: LFS needs to be synchronized
**Describe the bug**
LFS requires synchronization if used from multiple threads.

**Set up (please complete the following information)**
  - nRF52840 Feather Express, 0.14.6 + commit aed854c1069050d5aa5c2821eb4c9fb744d240dc
  - Log and sketch at https://gist.github.com/henrygab/b7d5376a09e8a488483347fc100a1ba4

**To Reproduce**
1. Build the sketch and upload to supported nRF52840 board
2. Watch log

**Expected behavior**
Few (if any) bad blocks detected

**Additional context**
Turns out that LFS requires, when multiple threads may use it simultaneously, that locking be added (e.g., with mutex).

See partial fix via issue #350 and PR #372.
See [questions](https://github.com/ARMmbed/littlefs/issues/352) posted at littlefs repo.

### PR DESCRIPTION
**Pull request by henrygab**
Fix #350
Fix #325
Fix #227
Fix #222
Fix #393

@hathach -- This PR supercedes #372 (Guard against race conditions in Flash FS cache), as #72 was not really providing a proper fix of the underlying problem:

LFS itself is [not safe](https://github.com/ARMmbed/littlefs/issues/352) to call simultaneously from multiple contexts.

This PR solves this by wrapping the InternalFS API with a non-recursive mutex, as recommended.

I realize the PR uses newly declared wrapper functions.  I tried to avoid this, but the changes got messy quite quickly, mostly due to some of the macros used to verify return codes exiting the function (which would leak the mutex).  This is a reasonably clean solution, without the more drastic move to use of RAII objects such as [`std::lock_guard<>`](https://en.cppreference.com/w/cpp/thread/lock_guard).

### CODE REVIEW

**Comment by mattratto** [comment]
This is great - thanks Henry and all. I have seen a file corruption issue remaining with 372 (much more infrequent than before but still there). Wonderful to have this wrapped up.

**Comment by henrygab** [comment]
@mattratto  -- You're right!  This will be wonderful to have wrapped up.

It'd be great to have some indication that this resolves a real-world reported instance, such as your remaining corruption problem.  Would you be willing to reply confirming that you no longer see your remaining corruption after using this fix?  (after you are fairly confident, of course)

Let's hope this closes this one for good!

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp [hunk 1]
```diff
@@ -55,6 +56,14 @@ Adafruit_LittleFS::~Adafruit_LittleFS ()
 // Return true if mounted successfully else probably corrupted.
 // User should format the disk and try again
 bool Adafruit_LittleFS::begin (struct lfs_config * cfg)
+{
+  while (pdTRUE != xSemaphoreTake(_mutex,  portMAX_DELAY)) {}
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp]: I think we don't need to check the return with `portMAX_DELAY` since it literally means wait forever.

**Comment by hathach** [comment]
@henrygab  do you think we also need mutex for the `Adafruit_LittleFS_File` as well ?
 https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp

**Comment by hathach** [comment]
I make PR to your branch to unwrap the VERIFY_LFS() here, since it it a bit too much work to ask you to change, please let's me know what you think. 
https://github.com/henrygab/Adafruit_nRF52_Arduino/pull/5

**Comment by hathach** [comment]
I still see the assert file with the stress test, we definitely need to wrap up the `Adafruit_LittleFS_File` as well

```
Task n3 writing ...
Task loop writing ...
Task loop writing ...
assertion "head >= 2 && head <= lfs->cfg->block_count" failed: file "/home/hathach/Arduino/hardware/adafruit/nrf52/libraries/Adafruit_LittleFS/src/littlefs/lfs.c", line 1235, function: lfs_ctz_extend
Task high writing ...
Task n3 writing ...
Task n1 writing ...
Task n3 writing ...
```

File: cores/nRF5/rtos.cpp [hunk 2]
```diff
@@ -45,6 +45,7 @@ static void _redirect_task(void* arg)
   while(1)
   {
     taskfunc();
+    delay(0);
```
[the remark this answers is not in the document]
Comment (henrygab) [reply cores/nRF5/rtos.cpp]: ok.  For some reason, when I traced through the yield() earlier, I thought it failed to call `tud_cdc_write_flush()` … but that is not the case … it was my error.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp (hunk 1 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp]: I did not realize that there were no other error conditions here.  You are correct again.

**Comment by henrygab** [comment]
> @henrygab  do you think we also need mutex for the Adafruit_LittleFS_File as well ?

Yes, I think we need to also use the mutex when lfs APIs are used from within `Adafruit_LittleFS_File`.
Let me see if I can create a small patch, likely by declaring a friend function (or two).

**Comment by henrygab** [comment]
@hathach -- the `Adafruit_LittleFS_File` public APIs appear to call into other public APIs, and thus would deadlock if simply ensuring the lock is acquired at each public API function entry / released at each exit.

I understand that you have indicated that you do not prefer the use of a wrapper function.  I am happy to consider alternatives, but believe the safest change is to wrap each APIs that is called from  another public API, so as to allow the serialization without major changes to the existing, tested, code flow.

What do you think?

**Comment by henrygab** [comment]
@hathach To maximize working time, I've gone ahead and put forward change that continues to work for the stress test.

It was not as simple as I had hoped.  Two issues in particular arose:

1. Because the `Adafruit_LittleFS_File` constructors were public, it was not possible to modify them without breaking the existing API.  Although I preferred otherwise, I added some friendship between the classes.

2. The implementation of various `Adafruit_LittleFS_File` functions called back into its own public API.  This meant that either a recursive mutex would be required (not a great solution), or that some of those public functions would need convert to wrappers around private functions.  I chose the latter solution of (limited) wrapper functions where needed.

3. As before, the use of the VERIFY() macros had to be unwound.  This raises the possibility of typos or logic inversion.  

Accordingly, I strongly request your careful code review and testing for commit 2a2f771.

**Comment by henrygab** [comment]
Rebase changes to be based from 0.15.0 ...

**Comment by mattratto** [comment]
I haven’t tried the rebase, but use of the previous version still results in periodic lockups - only on sequential removal of files. This is happening after the saving of approximately 100 separate 50byte files. When I loop through and remove them, sometimes the code halts. I haven’t yet run this with debug on, but once I do, I will post more info. 

I am wondering if I am not allowing enough of a delay between each remove, though from my reading of the new code this should not be an issue. 

I should add that this is occurring in a production environment which includes Bluetooth transactions. 

Matt

**Comment by mattratto** [comment]
Another note - this is occurring on brand new boards. I am not running a file system format before placing files on the flash, following initial install of software. Is it possible that reliability would be increased by adding an initial format prior to adding files?

**Comment by hathach** [comment]
Sorry for late response, is busy migrating from travis to github action, and bunch o f unnamed work at the end of year. Will look at this next.

**Comment by henrygab** [comment]
@mattratto -- 

Question: Are your files in the root directory, or are they all in a subdirectory that only you use?

**_Why:_** 

As a test, if you they were in root, and you moved all your files out into a subdirectory, would you still see a problem?

* If yes, then I'm intrigued... Could the softdevice also doing some access to the flash that fundamentally conflicts? Could it be that it cannot be "safe" to cache data at all when the softdevice is enabled?
* If no, then while not definitive (cannot easily tell difference between move from 99% --> 99.999% vs. to 100%), using the subdirectory may be a quick way to reduce instances of the problem?

**Comment by mattratto** [comment]
They were all in root. I’m moving to subdirectory and continuing to test. Is there anything fancy I should be doing with this? I’ve just appended /data/ to the file names for the write, and open /data/ for the reads and deletes. 

As always, my thanks Henry!

**Comment by henrygab** [comment]
_First, I have very little understanding of what the SD does.  This currently is limiting me to (hopefully educated) guesses on how this might occur.  That said..._

No, nothing fancy.  A subdirectory is all that's needed to get the potential reduction in interactions.

@hathach -- do you know when, why, and how the SD is saving bluetooth pairing data to flash?

**Comment by mattratto** [comment]
So I’ve put my data files in a directory and now, instead of deleting them individually, I delete and recreate the directory. Either the use of the directory, or this new deletion process seems to have resolved remaining issues. I am of course continuing to test, but looking good so far!

**Comment by henrygab** [comment]
@mattratto That data supports my current suspicion that the softdevice is messing with (writing directly to) sectors that Adafruit_LittleFS is using.

_(( I'm curious if there is any repro without sd enabled, but I can no longer repro the issue with this branch ))_

Can you get a repro if you go back to the prior behavior (saving in root directory), and *not* enable the softdevice / bluetooth?  Obviously, this presumes you have multiple tasks that each use the filesystem.

If you can repro even without the softdevice enabled, then something else is awry.

**Comment by henrygab** [comment]
@mattratto -- Matt, I want to be clear that, if the SD is the cause of corruption by writing to the LFS file system without being serialized, using a subdirectory will only make the problem much more rare, and not eliminate it entirely.

This is because there are still globally shared data structures on the media, so if/when certain conditions get hit, it would be more likely to cause conflict.

I think your prior method of deleting many files in sequence may have been a good test case _(but also good to know the recursive directory deletion can also further reduce the likelihood of conflict with SD)_.

**Comment by hathach** [comment]
Sorry for another delay, was busy with other works lately. 

> @hathach -- do you know when, why, and how the SD is saving bluetooth pairing data to flash?

To be clear SD doesn't write to LFS, only the Bluefruit library save information to LFS when
- Paired with an new device
- CCCD of bonded device is changed (enabled or disabled)

CCCD changes occurs more often then pairing with new device, if there is conflict, it is probably it.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h [hunk 3]
```diff
@@ -69,13 +75,21 @@ class File : public Stream
...
+
+    bool isOpen(void);
     char const* name (void);
 
     bool isDirectory (void);
     File openNextFile (uint8_t mode = FILE_O_READ);
     void rewindDirectory (void);
 
+    // Has to be public, in order to grant 'friend' permissions to Adafruit_LittleFS private member _mutex
+    void DoNotCallFromOutsideClass_LockFilesystem(void);
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h]: @henrygab  Do we need to lock the entire file system when working with File API, I am thinking we could have an mutex for each file/folder to ensure that there are 2 threads that open the same file/directory instead of locking the whole file system.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h [hunk 4]
```diff
@@ -69,13 +75,21 @@ class File : public Stream
     uint32_t size (void);
 
     void close (void);
+
+    __attribute__((deprecated("Recommend use of isOpen() for clarity")))
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h]: it is how Arduino design and used to test the file through out its examples. Don't be bothered with it ;)

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h [hunk 5]
```diff
@@ -69,13 +75,21 @@ class File : public Stream
...
     operator bool (void);
+
+    bool isOpen(void);
     char const* name (void);
 
     bool isDirectory (void);
     File openNextFile (uint8_t mode = FILE_O_READ);
     void rewindDirectory (void);
 
+    // Has to be public, in order to grant 'friend' permissions to Adafruit_LittleFS private member _mutex
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h]: @henrygab as long as it works, maybe we should expose the LFS lock/unlock() file system to public :)

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 6]
```diff
@@ -46,9 +46,20 @@ File::File (Adafruit_LittleFS &fs)
...
 {
+  // public constructor calls public API open(), which will obtain the mutex
   this->open(filename, mode);
 }
 
+File::File (uint8_t differentiator, char const *filename, uint8_t mode, Adafruit_LittleFS &fs)
+ : File(fs)
+{
+  // private constructor calls private API _open(), which does NOT obtain the mutex
+  (void)differentiator;
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: could you tell me what is the `differentiator` for ?

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 7]
```diff
@@ -130,151 +152,260 @@ bool File::open (char const *filepath, uint8_t mode)
...
 
 size_t File::write (uint8_t const *buf, size_t size)
 {
-  VERIFY(!_is_dir, 0);
-
-  lfs_ssize_t wrcount = lfs_file_write(_fs->getFS(), _file, buf, size);
-  VERIFY(wrcount > 0, 0);
+  lfs_ssize_t wrcount = 0;
+  this->DoNotCallFromOutsideClass_LockFilesystem();
+  if (!this->_is_dir)
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: this should be checked before attempting to lock the fs

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 8]
```diff
@@ -130,151 +152,260 @@ bool File::open (char const *filepath, uint8_t mode)
...
+    };
+  }
+  this->DoNotCallFromOutsideClass_UnlockFilesystem();
   return wrcount;
 }
 
 int File::read (void)
 {
-  VERIFY(!_is_dir, -1);
+  // this thin wrapper relies on called function to synchronize
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: _is_dir shouldn't be dropped

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 9]
```diff
@@ -130,151 +152,260 @@ bool File::open (char const *filepath, uint8_t mode)
...
       _file = NULL;
     }
   }
 }
 
+[[deprecated("Recommend use of isOpen() for clarity")]]
 File::operator bool (void)
+{
+  bool ret = false;
+  this->DoNotCallFromOutsideClass_LockFilesystem();
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: there is no need to lock fs for this function. We can also make bool() as inline verion of isOpen()

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 10]
```diff
@@ -130,151 +152,260 @@ bool File::open (char const *filepath, uint8_t mode)
...
 
+// WARNING -- although marked as `const`, the values pointed
+//            to may change.  For example, if the same File
+//            object has `open()` called with a different
+//            file or directory name, this same pointer will
+//            suddenly (unexpectedly?) have different values.
 char const* File::name (void)
 {
-  return _name;
+  this->DoNotCallFromOutsideClass_LockFilesystem();
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: I don't see why we have to lock fs for these API(), it just a simple return.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 11]
```diff
@@ -130,151 +152,260 @@ bool File::open (char const *filepath, uint8_t mode)
...
+  char const* ret = this->_name;
+  this->DoNotCallFromOutsideClass_UnlockFilesystem();
+  return ret;
 }
 
 bool File::isDirectory (void)
 {
-  return _is_dir;
+  this->DoNotCallFromOutsideClass_LockFilesystem();
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: same as above

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 12]
```diff
@@ -130,151 +152,260 @@ bool File::open (char const *filepath, uint8_t mode)
...
+}
+bool File::isOpen(void)
+{
+  bool ret = 0;
+  this->DoNotCallFromOutsideClass_LockFilesystem();
+  ret = this->_isOpen();
+  this->DoNotCallFromOutsideClass_UnlockFilesystem();
+  return ret;
+}
+bool File::_isOpen(void)
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: I think we don't need _isOpen() variant, just put this implementation as isOpen()

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp [hunk 13]
```diff
@@ -130,151 +152,260 @@ bool File::open (char const *filepath, uint8_t mode)
...
+  this->DoNotCallFromOutsideClass_LockFilesystem();
+  if (!this->_is_dir)
+  {
+    ret = lfs_file_read(_fs->getFS(), _file, buf, nbyte);
+  }
+  this->DoNotCallFromOutsideClass_UnlockFilesystem();
+  return ret;
 }
 
 int File::peek (void)
```
Comment (hathach) [inline libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: I think peek() is safe as it is

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 12 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: The `_isOpen()` is necessary still because this function was used in other internal APIs, while the mutex was already taken.  In order to keep the same code flow and readability, this API is necessary to have as an internal function.  See, for example, `_open()` and `_close()`.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 11 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: The member variable `_is_dir` can be modified by a call to `File::open( … )`.  Therefore, access to the function must be serialized.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 10 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: The member variable `_name` can be modified by a call to `File::open( … )`.  Therefore, access to the function must be serialized.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 9 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: OK.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 7 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: I disagree.  The same `File` object can change from a file to a directory, such as through a call to `File::open(char const *filepath, uint8_t mode)`.  Therefore, it is necessary to lock before checking the member variable `_is_dir`.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 6 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: Good question.

This was a relic of a prior attempted solution, before `open()` was split into `open()` as a wrapper and `_open()` as the internal function without mutex.

<detail>
<summary>Background, in case you wonder...</summary>

Let me give some background on existing constructors and use:

* `File::File (Adafruit_LittleFS &fs)` -- This public constructor simply keeps a copy of the pointer.  No lock used.

* `File::File (char const *filename, uint8_t mode, Adafruit_LittleFS &fs) : File(fs)` -- This calls the above constructor, but then calls `open()`, which will obtain the mutex as part of the open().

At the time, I believe `openNextFile()` created the return value by using the second constructor (with the filepath + mode).  Therefore, it was necessary for the mutex to **NOT** be acquired to call that constructor, to avoid deadlock.  Obviously, this was not OK, so I added the private constructor with a differentiating argument, so it would only be callable from within the `File` class.

</detail>

But, as your sharp eyes noticed, this constructor is no longer necessary.  I've removed it now.

Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: Background, in case you wonder...

Let me give some background on existing constructors and use:

* `File::File (Adafruit_LittleFS &fs)` -- This public constructor simply keeps a copy of the pointer.  No lock used.

* `File::File (char const *filename, uint8_t mode, Adafruit_LittleFS &fs) : File(fs)` -- This calls the above constructor, but then calls `open()`, which will obtain the mutex as part of the open().

At the time, I believe `openNextFile()` created the return value by using the second constructor (with the filepath + mode).  Therefore, it was necessary for the mutex to **NOT** be acquired to call that constructor, to avoid deadlock.  Obviously, this was not OK, so I added the private constructor with a differentiating argument, so it would only be callable from within the `File` class.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h (hunk 5 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h]: Ok.

Because this PR fixes data corruption, I think it is important to accept even if you want to change some function names later.

Separately, if you want the design to better hide this, I would recommend following the PIMPL (Pointer-to-Implementation) solution.  This would allow 100% hiding of all the non-public APIs, and the interactions between the FS / File abstractions, without exposing any of this internal shared locking.  However, changing to PIMPL would be a bigger architectural change … my goal was to minimize changes while serializing access to LFS APIs.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h (hunk 4 above)
Comment (henrygab) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h]: Ok...

**Comment by hathach** [comment]
hmm, look like you are too quick, I made a modification and submit it as PR (as usual) to your branch, but look like github has difficulty to pick up the differences.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 7 above)
Comment (hathach) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: IMHO, it is over-engineer,  I don't see use case where user change want to change it to other filepath in another thread out of context.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp (hunk 12 above)
Comment (hathach) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp]: I mean there is no need to lock mutex when checking with _file and _dir member. They should be reachable all time.

File: libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h (hunk 5 above)
Comment (hathach) [reply libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h]: No, I don't need any fancy way to absolute hide API from user. I would simply add underscore to `_lock/_unlock` public API  with comment saying it is intended to be used internally  and expect user not to call it :D
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/src/bluefruit.h#L239

**Comment by hathach** [comment]
Thank you very much @henrygab for spending lots of time fixing this issue. This has been draining a lot more time than expected ( and I am got pulled to work on other things meanwhile). I am very much appreciated for your time and effort. Looking forward to see more of your PRs in the future :)

**Comment by henrygab** [comment]
@hathach -- I am humbled by the many volunteers, without whose help (reporting, testing the many incomplete fixes, and final validation) this would not have been possible, including:
* @czuvich
* @matthewswilson
* @mattratto
* @jeremypoulter
* @jpconstantineau
* @shaoyuan1943

A special thanks also to @geky for helping me understand LFS!

**Comment by mattratto** [comment]
Amazing! Great to watch this work being done!

**Comment by hathach** [comment]
> @hathach -- I am humbled by the many volunteers, without whose help (reporting, testing the many incomplete fixes, and final validation) this would not have been possible, including:
> 
> * @czuvich
> * @matthewswilson
> * @mattratto
> * @jeremypoulter
> * @jpconstantineau
> * @shaoyuan1943
> 
> A special thanks also to @geky for helping me understand LFS!

Indeed, thank you everyone to help fixing this annoying bugs and be PATIENT with me :D

**Comment by mattratto** [comment]
HI all, and specifically Henry, after months of no corruption issues, I have now seen 5 issues, exhibited with both Adafruit BSP 0.16.0 and with Adafruit BSP 0.20.5 (most recent release.) In each case, the error is the same LFS 494 Corrupted Directory blocks. It is possible that these devices had an older version of the BSP installed previously and thus the corruption may have occurred while using an older version of the Adafruit littlefs libraries. It is resolved by a format, and has not reoccurred in any of the above examples. However, I am wondering how I might insulate my code against corruption issues. 

My main problem is that when my code runs into a corruption issue, it locks up. Does anyone have any suggestions how I could prevent this? I would like to show an error message and potentially kick off a format when the code encounters file corruption, but I have no idea how to do this since the lock up occurs while executing a file open. 

thanks, 

Matt

**Comment by mattratto** [comment]
In the interests of full disclosure, below is the code that is locking up when it encounters an error. If this is really a code rather than a library issue, I do apologize: 
InternalFS.begin(); //start file system
  File item(InternalFS);
  File dir("data/", FILE_O_READ, InternalFS);
    while( (item = dir.openNextFile(FILE_O_READ)) )
  {  
    String filename = item.name(); 
    if(filename.indexOf("data") == 0) {  
    uint32_t readlen;
    char buffer[999] = { 0 };
    readlen = item.read(buffer, sizeof(buffer));
    item.close();
    for (int e=0; e<readlen; e++) { //now parse and separate 
    Serial.print(buffer[e]); 
 }
 Serial.println("---"); 
 }
 }
dir.close();
}

**Comment by mattratto** [comment]
<script src="https://gist.github.com/mattratto/af60c80131fb506d64221a539ba781d6.js"></script>

**Comment by mattratto** [comment]
after further thought, am thinking this is a code issue rather than a library issue per se. For anyone who wanders by, I realized that the 'Internal_ListFiles' example does not lock up, but my code above does. The only difference is that the example code only grabs the file names, but I get the names but also try to read the file contents. So I am wondering if there is a way to check the file integrity prior to attempting to read - maybe in fact, the item.name read is returning an error code?

**Comment by hathach** [comment]
@mattratto the file system should done the checking for us, once the FS is corrupted, it is  too hard to check that, since you need to understand how the files is stored on the flash and understand how these inode chain work etc... 

Are you still seeing corruption issue with latest library ?

**Comment by mattratto** [comment]
@hathach I am getting file corruption error messages when running code with latest library. However, I do not know if they were created by the library, or occurred when running an older library, prior to update to 0.20.5 BSP. These show up when I run Internal_ListFiles example code and seem to be happening around the use of openNextFile. I went and looked at this function in Adafruit_LittleFS_file.cpp and found  on line 393: 

   (void)ret._open(filepath, mode); // return value is ignored ... caller is expected to check isOpened()

I couldn't find isOpened, but am now trying isOpen() on each item prior to proceeding: 

while( (item = dir.openNextFile(FILE_O_READ)) )
  {
    if (item.isOpen()){ 

I will test this and report back.

**Comment by hathach** [comment]
@mattratto I see your problem now, since this PR is merged and closed. You should really re-test the library with newly format drive, if you still have issue with latest code then. Feel free to open an new issue, that make following it easier ( your could point a ref link to this if needed).

**Comment by mattratto** [comment]
OK. Will do. Thanks @hahatch


Matt Ratto
Associate Professor
Bell University Labs Chair in Human-Computer Interaction
Faculty of Information
University of Toronto
@mattratto
